name: cs224w
channels:
  - defaults
dependencies:
  - pip=19.2.3
  - python=3.7.4
  - matplotlib=3.1.1
  - numpy=1.17.2
  - pip:
    # - pyqt5==5.13.1
    - scipy==1.3.1
    # - torch==1.3.0
    # - torch-cluster==1.4.5
    # - torch-geometric==1.3.2
    # - torch-scatter==1.3.2
    # - torch-sparse==0.4.3
    # torch doesn't intall correctly
    # do this manually
    # pip install torch (with commands from official website)
    # pip install --no-cache-dir torch-scatter
    # pip install --no-cache-dir torch-sparse
    # pip install --no-cache-dir torch-cluster
    # pip install torch-geometric
    # pip install networkx
    - torch
    - torch-scatter --install-option="--no-cache-dir"
    - torch-sparse --install-option="--no-cache-dir"
    - torch-cluster --install-option="--no-cache-dir"
    - torch-geometric
    - networkx

