name: cs224w
channels:
  - defaults
  - pip:
    - chardet==3.0.4
    - decorator==4.4.0
    - googledrivedownloader==0.4
    - h5py==2.10.0
    - idna==2.8
    - isodate==0.6.0
    - joblib==0.14.0
    - networkx==2.4
    - numpy=1.17.2
    - pandas==0.25.2
    - plyfile==0.7.1
    - pyqt5==5.13.1
    - pyqt5-sip==4.19.19
    - rdflib==4.2.2
    - requests==2.22.0
    - scikit-learn==0.21.3
    - scipy==1.3.1
    - torch==1.3.0
    - torch-cluster==1.4.5
    - torch-geometric==1.3.2
    - torch-scatter==1.3.2
    - torch-sparse==0.4.3
    - urllib3==1.25.6

