name: cs224w
channels:
  - defaults
dependencies:
  - pip=19.2.3
  - python=3.7.4
  - matplotlib=3.1.1
  - numpy=1.17.2
  - pip:
    - pyqt5==5.13.1
    - scipy==1.3.1
    - fancyimpute
    # torch doesn't intall correctly
    # do this manually
    # pip install torch (with commands from official website)
    # pip install --no-cache-dir torch-scatter (diferent for cuda)
    # pip install --no-cache-dir torch-sparse (diferent for cuda)
    # pip install --no-cache-dir torch-cluster (diferent for cuda)
    # pip install torch-geometric==1.4.2

